openapi: 3.0.0
info:
  title: GetCurrentBalance API
  version: 1.0.0
  description: API for retrieving the current balance, including income and expenses.

paths:
  /balance:
    get:
      summary: Get current balance
      description: Retrieves the current balance, including income and expenses.
      responses:
        '200':
          description: Successfully retrieved the current balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIBalanceDTO'
        '404':
          description: Balances not found.
        '500':
          description: Internal server error when retrieving the balance.
        '503':
          description: Database connection error.

components:
  schemas:
    APIBalanceDTO:
      type: object
      properties:
        current:
          type: integer
          description: The current balance
          example: 10000
        income:
          type: integer
          description: The current income
          example: 4000
        expenses:
          type: integer
          description: The current expenses
          example: 2000
      required:
        - current
        - income
        - expenses
