openapi: 3.0.0
info:
  title: GetAllBudgets API
  version: 1.0.0
  description: API for retrieving all budgets.

paths:
  /budget:
    get:
      summary: Get all budgets
      description: Retrieves all budgets.
      responses:
        '200':
          description: All budgets successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/APIBudgetDTO'
        '404':
          description: Budgets not found.
        '500':
          description: Internal server error occurred while retrieving the budgets.
        '503':
          description: Database connection error.

components:
  schemas:
    APIBudgetDTO:
      type: object
      properties:
        category:
          type: string
          description: The category of the budget.
          example: "General"
        maximum:
          type: integer
          description: The maximum amount of the budget.
          example: 100
        theme:
          type: string
          description: The theme color of the budget in hex format.
          example: "#000000"
      required:
        - category
        - maximum
        - theme
