openapi: 3.0.0
info:
  title: Budget API
  version: 1.0.0
  description: API for managing budgets.

paths:
  /budget/deleteBudget:
    delete:
      summary: "Delete an existing budget"
      description: "Deletes an existing budget based on the specified category."
      operationId: "deleteBudget"
      requestBody:
        description: "Details of the budget category to be deleted"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APICategoryDTO'
      responses:
        '204':
          description: "Budget successfully deleted. No content returned."
        '404':
          description: "Budget not found."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Budget not found.'
        '500':
          description: "Server error occurred while deleting the budget."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Error while deleting the budget: [Error details]'
        '503':
          description: "Database connection error."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Database connection error: [Error details]'

components:
  schemas:
    APICategoryDTO:
      type: object
      required:
        - category
      properties:
        category:
          type: string
          description: "The category of the budget to be deleted."
          example: "General"
