openapi: 3.0.0
info:
  title: AddNewBudget API
  version: 1.0.0
paths:
  /budget/addNewBudget:
    post:
      summary: Add a new budget
      description: Creates a new budget with the given category, maximum amount, and theme color.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: "General"
                maximum:
                  type: integer
                  example: 100
                theme:
                  type: string
                  example: "#000000"
              required:
                - category
                - maximum
                - theme
      responses:
        '201':
          description: Budget successfully created
        '400':
          description: Fehlerhafte Anfrage, wenn die Eingabedaten unvollständig oder ungültig sind.
        '500':
          description: Interner Serverfehler, wenn ein Fehler beim Erstellen des Budgets auftritt.