openapi: 3.0.0
info:
  title: AddNewBudget API
  version: 1.0.0
  description: API for adding a new budget.

paths:
  /budget/addNewBudget:
    post:
      summary: Add a new budget
      description: Creates a new budget with the specified category, maximum amount, and theme color.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: "General"
                maximum:
                  type: integer
                  example: 100
                theme:
                  type: string
                  example: "#000000"
              required:
                - category
                - maximum
                - theme
      responses:
        '201':
          description: Budget successfully created.
        '400':
          description: Bad request, if the input data is incomplete or invalid.
        '500':
          description: Internal server error when creating the budget.
        '503':
          description: Database connection error.
