openapi: 3.0.0
info:
  title: Pots API
  version: 1.0.0
  description: API for managing pots (e.g., savings goals)

paths:
  /pots/editPot:
    put:
      summary: "Edit an existing pot"
      operationId: "editPot"
      tags:
        - Pots
      requestBody:
        description: "Details of the pot to be edited"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIEditedPotDTO'
      responses:
        '200':
          description: "Pot successfully updated."
        '404':
          description: "Pot not found."
        '500':
          description: "Server error occurred while editing pot."
        '503':
          description: "Failed to connect to the database."

components:
  schemas:
    APIEditedPotDTO:
      type: object
      required:
        - id
        - name
        - target
        - total
        - theme
      properties:
        id:
          type: integer
          example: 1
          description: "The unique ID of the pot."
        name:
          type: string
          example: "Holiday"
          description: "The name of the pot."
        target:
          type: number
          format: float
          example: 3000.0
          description: "The target balance of the pot."
        total:
          type: number
          format: float
          example: 2000.0
          description: "The current balance of the pot."
        theme:
          type: string
          example: "#277C78"
          description: "The color theme of the pot."
