openapi: 3.0.0
info:
  title: Pots API
  description: API for managing financial pots.
  version: 1.0.0
paths:
  /pots/addNewPot:
    post:
      summary: "Add new pot"
      description: "Adds a new financial pot with the specified details."
      operationId: "addNewPot"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIPotDTO'
            example:
              name: "Laptop"
              target: 2400
              total: 2000
              theme: "#FFFFFF"
      responses:
        '201':
          description: "New pot successfully added."
        '500':
          description: "Server error occurred while adding the new pot."
        '503':
          description: "Error connecting to the database."

components:
  schemas:
    APIPotDTO:
      type: object
      properties:
        name:
          type: string
          description: "The name of the pot (e.g., 'Laptop')."
          example: "Laptop"
        target:
          type: integer
          description: "The target amount for the pot (e.g., 2400)."
          example: 2400
        total:
          type: integer
          description: "The current amount in the pot (e.g., 2000)."
          example: 2000
        theme:
          type: string
          description: "The theme color of the pot in hex format (e.g., '#FFFFFF')."
          example: "#FFFFFF"
      required:
        - name
        - target
        - total
        - theme
