openapi: 3.0.1
info:
  title: Pots API
  description: API for managing pots and adding money to them
  version: 1.0.0

paths:
  /pots/addMoneyToPot:
    put:
      summary: Add Money to an existing pot
      description: Adds a specified amount of money to an existing pot.
      operationId: addMoneyToPot
      requestBody:
        description: Details of the pot and the amount to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                potName:
                  type: string
                  description: The name of the pot
                  example: "Holiday"
                amountToAdd:
                  type: integer
                  description: The amount of money to add to the pot
                  example: 1000
              required:
                - potName
                - amountToAdd
      responses:
        '200':
          description: Money successfully added to Pot.
        '404':
          description: Pot not found.
        '500':
          description: Server error occurred while adding money to pot.
      tags:
        - Pots
