openapi: 3.0.0
info:
  title: GetAllPots API
  version: 1.0.0
  description: API to retrieve all pots.

paths:
  /pots:
    get:
      summary: "Get all pots"
      description: "Retrieves all pots, including their target amount, current amount, and color theme."
      operationId: "getPots"
      responses:
        '200':
          description: "Successfully retrieved all pots"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/APIPotDTO'
        '404':
          description: "Pots not found."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Pots not found."
        '500':
          description: "Internal server error when retrieving pots."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error getting pots: [Error details]"
        '503':
          description: "Failed to connect to the database."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Database connection error: [Error details]"

components:
  schemas:
    APIPotDTO:
      type: object
      properties:
        name:
          type: string
          description: "The name of the pot (e.g., 'Laptop')"
          example: "Laptop"
        target:
          type: integer
          description: "The target amount of the pot (e.g., 2400)"
          example: 2400
        total:
          type: integer
          description: "The current amount in the pot (e.g., 2000)"
          example: 2000
        theme:
          type: string
          description: "The color theme of the pot in hex format (e.g., '#FFFFFF')"
          example: "#FFFFFF"
      required:
        - name
        - target
        - total
        - theme
