openapi: 3.0.0
info:
  title: Pots API
  version: 1.0.0
  description: API for managing budget pots

paths:
  /deletePot:
    delete:
      summary: "Delete an existing pot"
      description: "Deletes an existing pot based on its name."
      operationId: deletePot
      requestBody:
        description: "The name of the pot to be deleted."
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIPotNameDTO'
      responses:
        '204':
          description: "Pot successfully deleted. No content is returned."
        '404':
          description: "Pot not found."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: "Server error occurred while deleting the pot."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: "Failed to connect to the database."

components:
  schemas:
    APIPotNameDTO:
      type: object
      properties:
        potName:
          type: string
          description: "The name of the pot to be deleted."
          example: 'Holiday'

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 500
        message:
          type: string
          example: 'Error while deleting pot: Database error'
        error:
          type: string
          example: 'Internal Server Error'
