openapi: 3.0.0
info:
  title: GetAllTransactions API
  version: 1.0.0
  description: API to retrieve all transactions.

paths:
  /transactions:
    get:
      summary: "Get all transactions"
      description: "Retrieves all transactions."
      operationId: getBalance
      responses:
        '200':
          description: "Successfully retrieved all transactions"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/APITransactionDTO'
        '404':
          description: "Transactions not found."
        '500':
          description: "Internal server error occurred while retrieving transactions."
        '503':
          description: "Failed to connect to the database."
      tags:
        - Transactions

components:
  schemas:
    APITransactionDTO:
      type: object
      properties:
        avatar:
          type: string
          description: "The image source of the transaction partner (e.g., an avatar image)"
          example: "/images/avatars/emma-richardson.jpg"
        name:
          type: string
          description: "The name of the transaction partner (e.g., 'Emma Richardson')"
          example: "Emma Richardson"
        category:
          type: string
          description: "The category of the transaction (e.g., 'General')"
          example: "General"
        date:
          type: string
          format: date-time
          description: "The date of the transaction in ISO-8601 format"
          example: "2024-08-19T14:23:11Z"
        amount:
          type: integer
          description: "The amount of the transaction (e.g., 100)"
          example: 100
        recurring:
          type: boolean
          description: "Indicates if the transaction is recurring (e.g., false)"
          example: false
      required:
        - avatar
        - name
        - category
        - date
        - amount
        - recurring
