export enum ColorDisplayNameEnum {
  GREEN = 'Green',
  YELLOW = 'Yellow',
  CYAN = 'Cyan',
  NAVY = 'Navy',
  RED = 'Red',
  PURPLE = 'Purple',
  TURQUOISE = 'Turquoise',
  BROWN = 'Brown',
  MAGENTA = 'Magenta',
  BLUE = 'Blue',
  GREY = 'Grey',
  ARMY = 'Army',
  PINK = 'Pink',
  GOLD = 'Gold',
  ORANGE = 'Orange',
  SEPIA = 'Sepia',
  WHITE = 'White',
}
