export enum ColorNameEnum {
  GREEN = 'green',
  YELLOW = 'yellow',
  CYAN = 'cyan',
  NAVY = 'navy',
  RED = 'red',
  PURPLE = 'purple',
  TURQUOISE = 'turquoise',
  BROWN = 'brown',
  MAGENTA = 'magenta',
  BLUE = 'blue',
  GREY = 'grey',
  ARMY = 'army',
  PINK = 'pink',
  GOLD = 'gold',
  ORANGE = 'orange',
  SEPIA = 'sepia',
  WHITE = 'white',
  BLACK = 'black',
}
