apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: {{ .Values.certificate.clusterIssuerName }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.hosts.frontend }}
    - {{ .Values.hosts.frontendWWW }}