name: unit testing and building

on:
  push:
    branches:
      - '*'

jobs:
  frontend-unit-tests:
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'
    uses: ./.github/workflows/stage2_testing.yml
    with:
      job_name: frontend-unit

  backend-unit-tests:
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'
    uses: ./.github/workflows/stage2_testing.yml
    with:
      job_name: backend-unit

  frontend-build:
    runs-on: ubuntu-latest

    needs: frontend-unit-tests

    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Build container image
        run: docker build -t registry.digitalocean.com/kephalosk/personal-finance-app:latest -f deployment/frontend.Dockerfile .

  backend-build:
    runs-on: ubuntu-latest

    needs: backend-unit-tests

    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Build container image
        run: docker build -t registry.digitalocean.com/kephalosk/nestjs-backend:latest -f deployment/backend.Dockerfile .
