name: versioning, testing, building, analyzing, linting, ui-testing, deploying and notifying

on:
  push:
    branches: 
      - 'master'

permissions:
  security-events: write
  checks: write

jobs:
  versioning:
    uses: ./.github/workflows/stage1_versioning.yml

  testing:
    uses: ./.github/workflows/stage2_testing.yml
    needs: versioning
    secrets: inherit

  building:
    uses: ./.github/workflows/stage3_building.yml
    needs: testing
    secrets: inherit

  analyzing:
    uses: ./.github/workflows/stage4_analyzing.yml
    needs: building
    secrets: inherit

  linting:
    uses: ./.github/workflows/stage5_linting.yml
    needs: analyzing
    secrets: inherit

  ui-testing:
    uses: ./.github/workflows/stage6_ui-testing.yml
    needs: linting
    secrets: inherit

  deploying:
    uses: ./.github/workflows/stage7_deploying.yml
    needs: ui-testing
    secrets: inherit

  notifying:
    uses: ./.github/workflows/stage8_notifying.yml
    needs: deploying
    secrets: inherit
    if: always()
    with:
      hasSucceeded: ${{ needs.deploying.result == 'success' }}
      isMaster: true