name: versioning, tests, build, image-scans, code-scans, linting, ui-tests, deploying and notifying

on:
  push:
    branches: 
      - 'master'

permissions:
  security-events: write
  checks: write

jobs:
  versioning:
    uses: ./.github/workflows/stage1_versioning.yml

  testing:
    uses: ./.github/workflows/stage2_testing.yml
    needs: versioning
    secrets: inherit

  building:
    uses: ./.github/workflows/stage3_building.yml
    needs: testing
    secrets: inherit

  image-analyzing:
    uses: ./.github/workflows/stage4_image-analyzing.yml
    needs: building
    secrets: inherit

  code-analyzing:
    uses: ./.github/workflows/stage5_code-analyzing.yml
    needs: image-analyzing
    secrets: inherit

  linting:
    uses: ./.github/workflows/stage6_linting.yml
    needs: code-analyzing
    secrets: inherit

  ui-testing:
    uses: ./.github/workflows/stage7_ui-testing.yml
    needs: linting
    secrets: inherit

  deploying:
    uses: ./.github/workflows/stage8_deploying.yml
    needs: ui-testing
    secrets: inherit

  notifying:
    uses: ./.github/workflows/stage9_notifying.yml
    needs: deploying
    with:
      hasFailed: ${{ needs.deploying.result == 'failure' && 'true' || 'false' }}
      isMaster: 'true'