name: linting

on:
  workflow_call

jobs:
  frontend-eslint-scan:
    runs-on: ubuntu-latest

    needs: [codeql-scan, gitleaks-scan]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint
        run: |
          cd frontend
          npx eslint .

  backend-eslint-scan:
    runs-on: ubuntu-latest

    needs: [codeql-scan, gitleaks-scan]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run ESLint
        run: |
          cd backend
          npx eslint src