name: ui-testing

on:
  workflow_call:

jobs:
  frontend-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Download PACKAGE_VERSION_FRONTEND Artifact
        uses: actions/download-artifact@v4
        with:
          name: PACKAGE_VERSION_FRONTEND
          path: .

      - name: Read PACKAGE_VERSION_FRONTEND
        id: read_package_version
        run: |
          PACKAGE_VERSION_FRONTEND=$(cat PACKAGE_VERSION_FRONTEND)
          echo "PACKAGE_VERSION_FRONTEND=$PACKAGE_VERSION_FRONTEND" >> $GITHUB_ENV

      - name: Pull image from registry
        run: docker pull registry.digitalocean.com/kephalosk/personal-finance-app:${{ env.PACKAGE_VERSION_FRONTEND }}

      - name: Run image from registry
        run: docker run -d -p 5173:80 registry.digitalocean.com/kephalosk/personal-finance-app:${{ env.PACKAGE_VERSION_FRONTEND }}

      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test ui-tests/e2e-tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/ui-tests/e2e-tests
          retention-days: 30

  frontend-gui:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Download PACKAGE_VERSION_FRONTEND Artifact
        uses: actions/download-artifact@v4
        with:
          name: PACKAGE_VERSION_FRONTEND
          path: .

      - name: Read PACKAGE_VERSION_FRONTEND
        id: read_package_version
        run: |
          PACKAGE_VERSION_FRONTEND=$(cat PACKAGE_VERSION_FRONTEND)
          echo "PACKAGE_VERSION_FRONTEND=$PACKAGE_VERSION_FRONTEND" >> $GITHUB_ENV

      - name: Pull image from registry
        run: docker pull registry.digitalocean.com/kephalosk/personal-finance-app:${{ env.PACKAGE_VERSION_FRONTEND }}

      - name: Run image from registry
        run: docker run -d -p 5173:80 registry.digitalocean.com/kephalosk/personal-finance-app:${{ env.PACKAGE_VERSION_FRONTEND }}

      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test ui-tests/gui-tests

      - name: Create Artifact for Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-integration
          path: frontend/ui-tests/gui-tests
          retention-days: 30

  create-vrts:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Download PACKAGE_VERSION_FRONTEND Artifact
        uses: actions/download-artifact@v4
        with:
          name: PACKAGE_VERSION_FRONTEND
          path: .

      - name: Read PACKAGE_VERSION_FRONTEND
        id: read_package_version
        run: |
          PACKAGE_VERSION_FRONTEND=$(cat PACKAGE_VERSION_FRONTEND)
          echo "PACKAGE_VERSION_FRONTEND=$PACKAGE_VERSION_FRONTEND" >> $GITHUB_ENV

      - name: Pull image from registry
        run: docker pull registry.digitalocean.com/kephalosk/personal-finance-app:${{ env.PACKAGE_VERSION_FRONTEND }}

      - name: Run image from registry
        run: docker run -d -p 5173:80 registry.digitalocean.com/kephalosk/personal-finance-app:${{ env.PACKAGE_VERSION_FRONTEND }}

      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test ui-tests/gui-tests --update-snapshots

      - name: Create Artifact for new vrt screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: new-vrts
          path: frontend/ui-tests/gui-tests
          retention-days: 30