name: code-scans

on:
  workflow_call

jobs:
  codeql-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript,typescript'
          build-mode: 'none'

      - name: Finalize CodeQL Database and Upload Results
        uses: github/codeql-action/analyze@v3
        with:
          output: './results'
          upload: 'always'
          upload-database: 'true'
          wait-for-processing: 'true'

  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}